[package]
name = "phalanxia/recs"
description = "An entity component system library written in Luau, for use in Roblox."
authors = ["AmaranthineCodices <git@lily.fyi>", "Madi <me@madi.pizza>"]
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = false
exclude = ["tests", "development-place.project.json", "testez.yml", "spec.lua", "stylua.toml", "selene.toml", "aftman.toml"]

[dependencies]
t = "osyrisrblx/t@3.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
